name: CI/CD Pipeline
on:
  push:
    branches: [ main ]
jobs:
  build-and-deploy:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: Build and Push Backend
        run: |
          cd backend
          docker build -t yourusername/flask-backend:latest .
          echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
          docker push yourusername/flask-backend:latest
      - name: Build and Push Frontend
        run: |
          cd frontend
          docker build -t yourusername/flask-frontend:latest .
          docker push yourusername/flask-frontend:latest
      - name: Deploy to SVR02
        run: |
          ssh user@192.168.100.102 'docker-compose -f /path/to/docker-compose.yml down && docker-compose -f /path/to/docker-compose.yml up -d'