name: CI/CD Pipeline
on:
  push:
    branches: [ main ]
jobs:
  build-and-deploy:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: Build and Push Backend
        run: |
          cd backend
          docker build -t sharthu/flask-backend:latest .
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -username "${{ secrets.DOCKER_USERNAME }}" --password-stdin
          docker push sharthu/flask-backend:latest
      - name: Build and Push Frontend
        run: |
          cd frontend
          docker build -t sharthu/flask-frontend:latest .
          docker push sharthu/flask-frontend:latest
      - name: Deploy to SVR02
        run: |
          ssh -i "id_rsa" sharthu@192.168.100.102 << 'EOF'
            # Download docker-compose.yml from GitHub
            curl -o /tmp/docker-compose.yml https://github.com/sharthu/flaskwebapp/blob/main/docker-compose.yml
            # Deploy using the downloaded file
            docker-compose -f /tmp/docker-compose.yml pull
            docker-compose -f /tmp/docker-compose.yml down
            docker-compose -f /tmp/docker-compose.yml up -d
            # Clean up
            rm /tmp/docker-compose.yml
          EOF